#!/usr/bin/env bash
# _emit.sh — turns CG_TREE (populated by _cg_walk) into a standalone
# completion script for bash, zsh, or fish. Sourced by entry.sh.
#
# Fidelity is intentionally uneven across shells, and that unevenness is
# documented rather than papered over:
#   - bash gets a full, context-aware COMPREPLY function walking the
#     whole parsed tree (shy is bash-first per docs/01-whitepaper.md).
#   - zsh gets a bashcompinit compatibility shim that reuses the exact
#     same bash function — correct by construction, not a second parser.
#   - fish gets native `complete` directives, but only for depth 0-1
#     (fish's data-driven completion primitives don't model exact
#     positional nesting past one subcommand without a custom completion
#     function per node, which is out of scope for v0.1).

# _cg_emit_bash TOOL — prints a self-contained bash completion function
# plus its `complete -F` registration.
_cg_emit_bash() {
    local tool="$1"
    local ident; ident="$(_cg_bash_ident "$tool")"

    printf "# Generated by shy completion-gen (--help-parsed introspection) for '%s'.\n" "$tool"
    printf '# Best-effort: derived from --help/-h text, not the tool'"'"'s own\n'
    printf "# completion generator (none worked — see 'shy completion-gen %s --json').\n" "$tool"
    printf '# Inspect before trusting for a security-sensitive tool.\n'
    printf '# Regenerate: shy completion-gen %s --install --force\n' "$tool"
    printf '_completion_gen_%s() {\n' "$ident"
    # shellcheck disable=SC2016  # literal text for the GENERATED script; must not expand here.
    printf '    local cur; cur="${COMP_WORDS[COMP_CWORD]}"\n'
    printf '    COMPREPLY=()\n'
    printf '    local -A __cg_subs=()\n'
    printf '    local -A __cg_flags=()\n'

    # Bash flatly refuses an empty string as an associative-array
    # subscript ("invalid array index") on every version tested — and
    # the ROOT node's path is exactly that empty string, i.e. the single
    # most important lookup (top-level completion) would always fail.
    # A sentinel key sidesteps it; "@root@" cannot collide with a real
    # subcommand path (paths are space-joined literal subcommand tokens,
    # and no CLI convention this plugin targets emits "@" as a token).
    local root_key='@root@'
    local rec path subs_csv flags_csv subs_words flags_words key
    for rec in "${CG_TREE[@]}"; do
        IFS=$'\x1f' read -r path subs_csv flags_csv <<< "$rec"
        subs_words="${subs_csv//,/ }"
        flags_words="${flags_csv//,/ }"
        if [[ -z "$path" ]]; then key="$(_cg_squote "$root_key")"; else key="$(_cg_squote "$path")"; fi
        printf '    __cg_subs[%s]=%s\n' "$key" "$(_cg_squote "$subs_words")"
        printf '    __cg_flags[%s]=%s\n' "$key" "$(_cg_squote "$flags_words")"
    done
    printf '    local __cg_root_key=%s\n' "$(_cg_squote "$root_key")"

    cat <<'INNER'
    local path="$__cg_root_key" i word candidate
    for (( i=1; i<COMP_CWORD; i++ )); do
        word="${COMP_WORDS[i]}"
        [[ "$word" == -* ]] && continue
        if [[ "$path" == "$__cg_root_key" ]]; then candidate="$word"; else candidate="$path $word"; fi
        if [[ -n "${__cg_subs[$candidate]+x}" || -n "${__cg_flags[$candidate]+x}" ]]; then
            path="$candidate"
        else
            break
        fi
    done
    local opts="${__cg_subs[$path]:-} ${__cg_flags[$path]:-}"
    COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
    return 0
INNER
    printf '}\n'
    printf 'complete -F _completion_gen_%s %s\n' "$ident" "$tool"
}

# _cg_emit_zsh TOOL — bashcompinit compatibility shim (see file header for
# the correctness-over-native-parser rationale).
_cg_emit_zsh() {
    local tool="$1"
    printf '#compdef %s\n' "$tool"
    printf '# Generated by shy completion-gen: zsh compatibility shim.\n'
    printf '# Loads bashcompinit and reuses the bash completion function\n'
    printf '# below rather than a native zsh _arguments spec.\n'
    printf 'autoload -Uz bashcompinit && bashcompinit\n'
    _cg_emit_bash "$tool"
}

# _cg_emit_fish TOOL — native `complete` directives, depth 0-1 only.
_cg_emit_fish() {
    local tool="$1"

    printf "# Generated by shy completion-gen (--help-parsed introspection) for '%s'.\n" "$tool"
    printf '# Depth-limited to one subcommand level: exact positional nesting\n'
    printf '# past that needs a custom fish completion function per node, out\n'
    printf '# of scope for v0.1. Use --shell bash for the full-depth tree.\n'

    local rec path subs_csv flags_csv depth cond sub flag
    for rec in "${CG_TREE[@]}"; do
        IFS=$'\x1f' read -r path subs_csv flags_csv <<< "$rec"
        depth=0
        [[ -n "$path" ]] && depth=$(wc -w <<< "$path")
        (( depth > 1 )) && continue

        if [[ "$depth" -eq 0 ]]; then
            cond="__fish_use_subcommand"
        else
            cond="__fish_seen_subcommand_from ${path}"
        fi

        if [[ -n "$subs_csv" ]]; then
            for sub in ${subs_csv//,/ }; do
                printf "complete -c %s -n '%s' -f -a '%s'\n" "$tool" "$cond" "$sub"
            done
        fi
        if [[ -n "$flags_csv" ]]; then
            for flag in ${flags_csv//,/ }; do
                if [[ "$flag" == --* ]]; then
                    printf "complete -c %s -n '%s' -l %s\n" "$tool" "$cond" "${flag#--}"
                elif [[ "$flag" == -* ]]; then
                    printf "complete -c %s -n '%s' -s %s\n" "$tool" "$cond" "${flag#-}"
                fi
            done
        fi
    done
}

# _cg_emit_json TOOL — diagnostics instead of a script (the `--json`
# convention docs/01-whitepaper.md prescribes for plugin reads). Hand-
# rolled (no jq dependency — plugins stay on the bash+git baseline).
_cg_emit_json() {
    local tool="$1"
    local node_count="${#CG_TREE[@]}"
    local sub_total=0 flag_total=0
    local rec path subs_csv flags_csv n

    for rec in "${CG_TREE[@]}"; do
        IFS=$'\x1f' read -r path subs_csv flags_csv <<< "$rec"
        if [[ -n "$subs_csv" ]]; then
            n=$(tr ',' '\n' <<< "$subs_csv" | grep -c .)
            sub_total=$((sub_total + n))
        fi
        if [[ -n "$flags_csv" ]]; then
            n=$(tr ',' '\n' <<< "$flags_csv" | grep -c .)
            flag_total=$((flag_total + n))
        fi
    done

    local warnings_json="[]"
    if [[ "${#CG_WARNINGS[@]}" -gt 0 ]]; then
        local w parts=()
        for w in "${CG_WARNINGS[@]}"; do
            parts+=("\"$(_cg_json_escape "$w")\"")
        done
        warnings_json="[$(_cg_join ',' "${parts[@]}")]"
    fi

    printf '{\n'
    printf '  "tool": "%s",\n' "$(_cg_json_escape "$tool")"
    printf '  "shell": "%s",\n' "$(_cg_json_escape "$CG_SHELL")"
    printf '  "method": "%s",\n' "$(_cg_json_escape "$CG_METHOD")"
    printf '  "nodes_parsed": %d,\n' "$node_count"
    printf '  "subcommands_found": %d,\n' "$sub_total"
    printf '  "flags_found": %d,\n' "$flag_total"
    printf '  "warnings": %s\n' "$warnings_json"
    printf '}\n'
}
